### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jethrolarson** [ramda/eslint-plugin-ramda#3]
You can just close this, but I figured I'd let y'all know.

I ran this against against a very large project that is using ramda extensively. I found 8 errors, all of which were valid and worth fixing. 

I compared time that lint took 
with eslint-plugin-ramda:
> 29.05s user 0.56s system 104% cpu 28.408 total

and without:

> 29.05s user 0.57s system 104% cpu 28.419 total

**Comment by haskellcamargo** [comment]
Thanks for your feedback! We've improved things now to support multiple kinds of call and soon will be adding new rules! It's amazing to see the project evolving!
