### ISSUE TITLE
Module prefixed names

### ISSUE THREAD

**Issue by polytypic** [ramda/eslint-plugin-ramda#7]
I gave this a quick spin and ran into a difficulty.  Namely, our code base generally imports Ramda as the `R` module and all references to Ramda functions are then prefixed with the module name.  Not seeing any lint issues, I changed a use of `R.pluck(...)` to `R.map(R.prop(...))` and I still didn't see any lint issues.  Then I changed it to `map(prop(...))` and got the lint issue I expected.  Is there a way to configure this plugin with a module prefix?

**Comment by haskellcamargo** [comment]
I've already started some tests on identifying these patterns and I'm implementing now support for both `map` and `R.map`, for example in [this branch](https://github.com/ramda/eslint-plugin-ramda/tree/specialized-names). After, we can make this configurable and try to check from where the names are being imported.
